// <auto-generated />
using System;
using Flux.Consolidado.Infrastructure.Storage.Configs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flux.Consolidado.Infrastructure.Storage.Migrations
{
    [DbContext(typeof(ConsolidadoContext))]
    partial class ConsolidadoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Flux.Consolidado.Domain.Entity.Entities.Consolidado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_inativacao");

                    b.Property<float>("Saldo")
                        .HasColumnType("REAL")
                        .HasColumnName("saldo");

                    b.HasKey("Id");

                    b.ToTable("consolidado", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
